name: Sign and deploy plugin to GitHub Releases
on: workflow_dispatch

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Read VERSION file
        id: getversion
        run: echo "::set-output name=version::$(cat VERSION)"
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Publish package
        run: ./gradlew zipDeployment -PsignPublications
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_SECRET }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSWORD }}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.getversion.outputs.version }}
          files: |
            *.zip
            LICENSE